local is_tty = (vim.fn.has("gui_running") == 0 and vim.env.TERM == "linux")

-- Set background and colorscheme name
vim.o.background = "dark"
vim.g.colors_name = "vim-earl-grey"

-- Helper function for highlights
local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

if is_tty then
    hi("Normal", { ctermfg=7, ctermbg=0 })
    hi("Error", { ctermfg=1, ctermbg=0 })
    hi("String", { ctermfg=2, ctermbg=0 })
    hi("Number", { ctermfg=3, ctermbg=0 })
    hi("Keyword", { ctermfg=5, ctermbg=0 })
    hi("Function", { ctermfg=4, ctermbg=0 })
    hi("Comment", { ctermfg=6, ctermbg=0 })
    hi("Visual", { ctermbg=7 })
    hi("CursorLine", { ctermbg=0 })
    hi("LineNr", { ctermfg=7, ctermbg=0 })
    hi("CursorLineNr", { ctermfg=0, ctermbg=7 })
    hi("MatchParen", { ctermfg=0, ctermbg=7, underline=true })
else
    -- Highlights
    hi("Error", { fg = "#8E5652", bg = "NONE", sp = "NONE", bold = false, underline = false, italic = false })
    hi("Type", { fg = "#605A52", bg = "NONE" })
    hi("Function", { fg = "#605A52", bg = "NONE" })
    hi("PreProc", { fg = "#886A44", bg = "NONE" })
    hi("Statement", { fg = "#84587E", bg = "NONE" })
    hi("NormalFloat", { fg = "#605A52", bg = "#F2EBE3" })
    hi("DiffDelete", { fg = "#8E5652", bg = "NONE" })
    hi("DiffAdd", { fg = "#737A4D", bg = "NONE" })
    hi("DiffChange", { fg = "#886A44", bg = "NONE" })
    hi("Normal", { fg = "#605A52", bg = "#FCFAF8" })
    hi("Visual", { bg = "#CBD2E1" })
    hi("LineNr", { fg = "#9C958B" })
    hi("Keyword", { fg = "#84587E" })
    hi("Operator", { fg = "#605A52" })
    hi("Delimiter", { fg = "#566A95" })
    hi("Directory", { fg = "#477A7B" })
    hi("Number", { fg = "#477A7B" })
    hi("String", { fg = "#737A4D" })
    hi("Constant", { fg = "#477A7B" })
    hi("Conditional", { fg = "#84587E" })
    hi("Repeat", { fg = "#84587E" })
    hi("MatchParen", { bg = "#CBD2E1", underline = true })
    hi("WarningMsg", { fg = "#886A44" })
    hi("ColorColumn", { bg = "#F7F3EE" })
    hi("SignColumn", {})
    hi("CursorLineNr", { bg = "#F7F3EE" })
    hi("Bold", { bold = true })
    hi("Underlined", { underline = true })
    hi("Italic", { italic = true })
    hi("LspReferenceText", { bg = "#F7F3EE" })
    hi("Pmenu", { bg = "#F7F3EE" })
    hi("PmenuSel", { bg = "#E0D0BD" })
    hi("Todo", { fg = "#477A7B", bg = "#F2EBE3" })
    hi("SpellBad", { fg = "#8E5652", underline = true })
    hi("SpellCap", { fg = "#566A95", underline = true })
    hi("SpellRare", { fg = "#886A44", underline = true })
    hi("SpellLocal", { fg = "#84587E", underline = true })
    hi("DiagnosticUnderlineError", { sp = "#A2625D", underline = true })
    hi("DiagnosticUnderlineWarn", { sp = "#9C7A4F", underline = true })
    hi("DiagnosticUnderlineHint", { sp = "#6076A4", underline = true })
    hi("DiagnosticUnderlineInfo", { sp = "#96648F", underline = true })
    hi("ErrorMsg", { fg = "#8E5652" })
    hi("LspReferenceRead", { bg = "#F7F3EE" })
end
